M48
; DRILL file {KiCad 7.0.6-0} date 2023 August 11, Friday 12:34:26
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-11T12:34:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X4.9445Y-2.2328
X4.9445Y-2.3128
X5.1445Y-2.2728
T2
X3.7284Y-5.7394
T3
X3.3372Y-3.7395
X4.9657Y-5.3681
T0
M30
